version: '10'
name: Android Open Source Project
type: release
variant: user
datetime: 1567667515
host: android
user: build
platform:
  ref: android-10.0.0_r2
  extra_remotes:
  - name: github
    fetch: https://github.com
  extra_projects:
  - name: RattlesnakeOS/android-prepare-vendor
    groups: device
    path: vendor/android-prepare-vendor
    remote: github
    revision: refs/heads/10.0
  remove_paths:
  - platform/prebuilts/qemu-kernel
  - platform/developers/samples/android
  - platform/developers/demos
  - device/generic/car
  - device/generic/qemu
  - device/lenaro/bootloader/arm-trusted-firmware
  - device/lenaro/bootloader/edk2
  - device/lenaro/bootloader/OpenPlatformPkg
  - device/lenaro/hikey
  - device/lenaro/hikey-kernel
  - device/lenaro/
  - device/google/atv
  - device/google/contexthub
  - device/google/muskie
  - device/generic/mips
  - device/google/hikey-kernel
  - device/generic/mips64
  - device/generic/mini-emulator-arm64
  - device/generic/mini-emulator-armv7-a-neon
  - device/generic/mini-emulator-mips
  - device/generic/mini-emulator-mips64
  - device/generic/mini-emulator-x86
  - device/generic/mini-emulator-x86_64
  - device/google/accessory/arduino
  - device/google/accessory/demokit
  remove_groups:
  - darwin
devices:
  bonito:
    kernel_name: bluecross
    kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
    factory_build: QP1A.190711.020
    factory_hash: 1f47c677bcb3ce427103a6388e3f07fb8a03789353cfd3baceb6c24e13b62f9a
  sargo:
    kernel_name: bluecross
    kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
    factory_build: QP1A.190711.020
    factory_hash: afb4dbc1df968aace547691a063a6bb6b2cc8cb6cc448b199a8b5b78803beb43
  crosshatch:
    kernel_name: bluecross
    kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
    avb_mode: vbmeta_chained
    factory_build: QP1A.190711.020
    factory_hash: 2eae0727565dc516a60e05f8502671d24e6d4b25770618d83d8a763147e259d3
  blueline:
    kernel_name: bluecross
    kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
    avb_mode: vbmeta_chained
    factory_build: QP1A.190711.020
    factory_hash: b5633fdfa34df0fccc4b6dc86799b1a2ee6a2fc1de1cd9c8a08da7703ad81ec2
  taimen:
    kernel_name: wahoo
    kernel_ref: origin/android-msm-wahoo-4.4-pie-qpr2
    avb_mode: vbmeta_simple
    factory_build: QP1A.190711.020
    factory_hash: 6f0233dd1c8faf8dad2324245e08ed18d8757eec99d724095941ea14e3eddeb2
  walleye:
    kernel_name: wahoo
    kernel_ref: origin/android-msm-wahoo-4.4-pie-qpr2
    avb_mode: vbmeta_simple
    factory_build: QP1A.190711.020
    factory_hash: fa9552eaef3531e2abae09b5e3aae510b7a052f6938a145dc1caed8b98a146c4
  marlin:
    kernel_name: marlin
    kernel_ref: origin/android-msm-marlin-3.18-pie-qpr2
    avb_mode: verity_only
    factory_build: QP1A.190711.020
    factory_hash: 2db5273a273a491fee3e175f3018830fc58015bdbacfedb589d67acf123156f8
  sailfish:
    kernel_name: marlin
    kernel_ref: origin/android-msm-marlin-3.18-pie-qpr2
    avb_mode: verity_only
    factory_build: QP1A.190711.020
    factory_hash: 0bb952229c861826b799084be63d834b63d227f22fb3d26a470d5d9b52b6d662
